export default {
    0x00: "Play animation",
    0x01: "Complete task",
    0x02: "Sync settings",
    0x03: "Set imposters",
    0x04: "Exiled",
    0x05: "Check name",
    0x06: "Set name",
    0x07: "Check colour",
    0x08: "Set colour",
    0x09: "Set hat",
    0x0a: "Set skin",
    0x0b: "Report dead body",
    0x0c: "Murder player",
    0x0d: "Send chat",
    0x0e: "Start meeting",
    0x0f: "Set scanner",
    0x10: "Send chat note",
    0x11: "Set pet",
    0x12: "Set start counter",
    0x13: "Enter vent",
    0x14: "Exit vent",
    0x15: "Snap to",
    0x16: "Close",
    0x17: "Voting complete",
    0x18: "Cast vote",
    0x19: "Clearote",
    0x1a: "Add vote",
    0x1b: "Close doors of type",
    0x1c: "Repair system",
    0x1d: "Set tasks",
    0x1e: "Update game data"
}